
### Login/register stuff

POST http://127.0.0.1:5000/api/v1/login
Content-Type: application/json

{
    "username": "test4",
    "password": "test5"
}

###

POST http://127.0.0.1:5000/api/v1/register
Content-Type: application/json

{
    "username": "test5",
    "password": "test5"
}


### Test local image testing upload

POST http://127.0.0.1:5000/api/v1/test_upload
Content-Type: multipart/form-data; boundary=----boundary123

------boundary123
Content-Disposition: form-data; name="image"; filename="local_image.jpg"
Content-Type: image/jpeg

< ./assets/lein_joker.jpg

------boundary123--

### 
