
### Login/register endpoints

POST http://127.0.0.1:5000/api/v1/login
Content-Type: application/json

{
    "username": "test8",
    "password": "test8"
}

###

# POST http://127.0.0.1:5000/api/v1/register
POST http://127.0.0.1:5000/api/v1/login
# POST http://159.223.99.186/api/v1/login
Content-Type: application/json

{
    "username": "newAccountTest",
    "password": "newAccountTest"
}


### New test local image upload

POST http://127.0.0.1:5000/api/v1/test_upload
Content-Type: application/octet-stream

< ./assets/lein_joker.jpg

### Test create contact from cluster (needs bearer token)
POST http://127.0.0.1:5000/api/v1/create_contact
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
    "cluster_id": "123",
    "contact_name": "John Doe"
}


### Get contacts
# GET http://159.223.99.186/api/v1/pull_contacts
GET http://127.0.0.1:5000/api/v1/pull_contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MTYzNzA4NiwianRpIjoiZDY2ZGEyMWQtMmFjZC00ZjBhLThlNDktZjcyYmMwMzU1NjkzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NDE2MzcwODYsImNzcmYiOiIxNjc1ZThkMi1lYmU5LTQzYjctYTI5ZC0wYzgwMzgwOWRkMjEiLCJleHAiOjE3NDE2NDA2ODZ9.jJMrBQ86xdB2Reod5aVN7IrINNT9UfaE6tPArJxdxbc


### Try to update a contact
# PATCH http://159.223.99.186/api/v1/edit_contact/5
PATCH http://127.0.0.1:5000/api/v1/edit_contact/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MTYzNzA4NiwianRpIjoiZDY2ZGEyMWQtMmFjZC00ZjBhLThlNDktZjcyYmMwMzU1NjkzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NDE2MzcwODYsImNzcmYiOiIxNjc1ZThkMi1lYmU5LTQzYjctYTI5ZC0wYzgwMzgwOWRkMjEiLCJleHAiOjE3NDE2NDA2ODZ9.jJMrBQ86xdB2Reod5aVN7IrINNT9UfaE6tPArJxdxbc
Content-Type: application/json

{
    "name": "guy"
}