// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC002kIKm4g5YpQFdwMEdBGGVv-GE83b7I',
    appId: '1:3606097715:web:716475fdf346adb2241846',
    messagingSenderId: '3606097715',
    projectId: 'senior-design-50b1e',
    authDomain: 'senior-design-50b1e.firebaseapp.com',
    storageBucket: 'senior-design-50b1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMVMJrUwneP3YenkJ59z-B-7KAJGThsvc',
    appId: '1:3606097715:android:1ca0883893e86e5f241846',
    messagingSenderId: '3606097715',
    projectId: 'senior-design-50b1e',
    storageBucket: 'senior-design-50b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71SSMk8DmlL0-_EgSkrpvnKB8EGxyZUg',
    appId: '1:3606097715:ios:ec4df6cf8eac91c2241846',
    messagingSenderId: '3606097715',
    projectId: 'senior-design-50b1e',
    storageBucket: 'senior-design-50b1e.firebasestorage.app',
    iosBundleId: 'com.example.visionbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71SSMk8DmlL0-_EgSkrpvnKB8EGxyZUg',
    appId: '1:3606097715:ios:ec4df6cf8eac91c2241846',
    messagingSenderId: '3606097715',
    projectId: 'senior-design-50b1e',
    storageBucket: 'senior-design-50b1e.firebasestorage.app',
    iosBundleId: 'com.example.visionbuzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC002kIKm4g5YpQFdwMEdBGGVv-GE83b7I',
    appId: '1:3606097715:web:7b179ba82ff4dd7f241846',
    messagingSenderId: '3606097715',
    projectId: 'senior-design-50b1e',
    authDomain: 'senior-design-50b1e.firebaseapp.com',
    storageBucket: 'senior-design-50b1e.firebasestorage.app',
  );

}